behaviors:
  CurriculumSPFencerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.003
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory:
        memory_size: 128
        sequence_length: 64
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    threaded: false
    keep_checkpoints: 5
    checkpoint_interval: 150000
    max_steps: 9600000
    time_horizon: 1024
    summary_freq: 6000
    self_play:
      save_steps: 60000
      team_change: 240000
      swap_steps: 24000
      window: 30
      play_against_latest_model_ratio: 0.2
      initial_elo: 1200.0

environment_parameters:
  timestep_reward:
    curriculum:
    - name: Phase1
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 300
        threshold: 0.3
      value: -1.0
    - name: Phase3
      value: 1.0
  footwork_enabled:
    curriculum:
    - name: Phase1
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 300
        threshold: 0.3
      value: 0.0
    - name: Phase3
      value: 1.0
  start_point_x_rand_coef:
    curriculum:
    - name: Phase1
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        threshold: 0.05
        min_lesson_length: 50
      value: 0.0
    - name: Phase2
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 50
        threshold: 0.1
      value: 0.5
    - name: Phase3Half
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 0.4
      value: 0.1
    - name: PhaseFinal
      value: 1.0
  start_point_z_rand_coef:
    curriculum:
    - name: Phase1
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 50
        threshold: 0.05
      value: 0.0
    - name: Phase2
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 50
        threshold: 0.1
      value: 0.5
    - name: Phase3Half
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 0.4
      value: 0.1
    - name: PhaseFinal
      value: 1.0
  tip_raycast_reward_threshold:
    curriculum:
    - name: Phase1
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 50
        threshold: 0.05
      value: 100.0
    - name: Phase2
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 50
        threshold: 0.1
      value: 75.0
    - name: Phase3
      completion_criteria:
        measure: reward
        behavior: CurriculumSPFencerBehavior
        signal_smoothing: true
        min_lesson_length: 100
        threshold: 0.5
      value: 60.0
    - name: PhaseFinal
      value: 30.0
  